export default [
  {
    dataId: 1,
    kullaniciId: 1,
    tarih: '22.01.2018',
    resim: 'https://randomuser.me/api/portraits/men/2.jpg',
    baslik: 'Güncel konular',
    icerik: 'veri madenciliği',
  },
  {
    dataId: 2,
    kullaniciId: 1,
    tarih: '28.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/3.jpg',
    baslik: 'Çok mühim olan şeçmeli ders',
    icerik: 'biyomedikal dersi çok tehlikeli almayın arkadaşlar',
  },
  {
    dataId: 3,
    kullaniciId: 1,
    tarih: '28.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/5.jpg',
    baslik: 'Hayata',
    icerik: 'Bakış Şeklim',
  },
  {
    dataId: 4,
    kullaniciId: 2,
    tarih: '26.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/6.jpg',
    baslik: 'ücretler ',
    icerik: 'Bu bir içeriktir',
  },
  {
    dataId: 5,
    kullaniciId: 2,
    tarih: '03.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/7.jpg',
    baslik: 'Bu Bir Not Başlığıdır',
    icerik: 'Bu bir içeriktir',
  },
  {
    dataId: 6,
    kullaniciId: 2,
    tarih: '05.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/8.jpg',
    baslik: 'Bu Bir Not Başlığıdır',
    icerik: 'Bu bir içeriktir',
  },
  {
    dataId: 7,
    kullaniciId: 2,
    tarih: '07.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/9.jpg',
    baslik: 'Bu Bir Not Başlığıdır',
    icerik: 'Bu bir içeriktir',
  },
  {
    dataId: 8,
    kullaniciId: 3,
    tarih: '19.02.2019',
    resim: 'https://randomuser.me/api/portraits/men/10.jpg',
    baslik: 'Bu Bir Not Başlığıdır',
    icerik: 'Bu bir içeriktir',
  },
  {
    dataId: 9,
    kullaniciId: 3,
    tarih: '30.03.2019',
    resim: 'https://randomuser.me/api/portraits/men/11.jpg',
    baslik: 'Bu Bir Not Başlığıdır',
    icerik: 'Bu bir içeriktir',
  },
  {
    dataId: 10,
    kullaniciId: 3,
    tarih: '03.04.2019',
    resim: 'https://randomuser.me/api/portraits/men/12.jpg',
    baslik: 'Bu Bir Not Başlığıdır',
    icerik: 'Bu bir içeriktir',
  },
];
