export default [
  {
    kullaniciId: 1,
    resim: 'https://randomuser.me/api/portraits/men/22.jpg',
    isim: 'Muhammed',
    soyisim: 'Çelebi',
    kullaniciAdi: 'mncsoft',
    sifre: '123',
  },
  {
    kullaniciId: 2,
    resim: 'https://randomuser.me/api/portraits/men/2.jpg',
    isim: 'Ahmet Can',
    soyisim: 'Önal',
    kullaniciAdi: 'ahmet',
    sifre: '123',
  },
  {
    kullaniciId: 3,
    resim: 'https://randomuser.me/api/portraits/men/3.jpg',
    isim: 'Ali',
    soyisim: 'Çolak',
    kullaniciAdi: 'ali1',
    sifre: '123',
  },
  {
    kullaniciId: 4,
    resim: 'https://randomuser.me/api/portraits/men/4.jpg',
    isim: 'Webster',
    soyisim: 'Çelebi',
    kullaniciAdi: 'can',
    sifre: '123',
  },
  {
    kullaniciId: 5,
    resim: 'https://randomuser.me/api/portraits/men/5.jpg',
    isim: 'Ahmet Can',
    soyisim: 'Çelebi',
    kullaniciAdi: 'ahmet123',
    sifre: '111',
  },
  {
    kullaniciId: 6,
    resim: 'https://randomuser.me/api/portraits/men/6.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 7,
    resim: 'https://randomuser.me/api/portraits/men/7.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 8,
    resim: 'https://randomuser.me/api/portraits/men/8.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 9,
    resim: 'https://randomuser.me/api/portraits/men/9.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 10,
    resim: 'https://randomuser.me/api/portraits/men/10.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 11,
    resim: 'https://randomuser.me/api/portraits/men/11.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 12,
    resim: 'https://randomuser.me/api/portraits/men/12.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 13,
    resim: 'https://randomuser.me/api/portraits/men/13.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 14,
    resim: 'https://randomuser.me/api/portraits/men/14.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 15,
    resim: 'https://randomuser.me/api/portraits/men/15.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 16,
    resim: 'https://randomuser.me/api/portraits/men/16.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
  {
    kullaniciId: 17,
    resim: 'https://randomuser.me/api/portraits/men/19.jpg',
    isim: 'Webster Burgess',
    soyisim: 'Çelebi',
    kullaniciAdi: 'EQUITOX',
    sifre: 'EQUITOX',
  },
];
